# Generated by Django 2.2.1 on 2020-10-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20201011_2340'),
        ('restaurants', '0003_auto_20201010_1423'),
    ]

    operations = [
    ]
