# Generated by Django 2.2.1 on 2020-10-12 16:06

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_merge_20201012_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address_location',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='web_page',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True, validators=[restaurants.validators.url_validation]),
        ),
    ]
