# Generated by Django 3.1.2 on 2020-10-02 07:39

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserRestaurant',
            fields=[
                ('document_type', models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('T.I', 'Tarjeta de identificación'), ('Passport', 'Pasaporte')], max_length=8)),
                ('document', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[accounts.validators.num_validation])),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('phone_num', models.CharField(max_length=12, unique=True, validators=[accounts.validators.num_validation])),
                ('date_of_birth', models.DateField()),
                ('email_address', models.EmailField(max_length=30, unique=True)),
                ('address_location', models.CharField(max_length=50)),
                ('state_delete', models.BooleanField(default=False)),
                ('state_disponibility', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_accounts/img_delivery_man')),
                ('type_of_vehicle', models.CharField(choices=[('bicycle', 'bicycle / monocycle'), ('motorcycle', 'motorcycle')], max_length=10)),
                ('vehicle_document', models.CharField(max_length=30)),
                ('id_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_user_restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userrestaurant'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_staff', models.CharField(default='Admin', max_length=20)),
                ('id_user_restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userrestaurant')),
            ],
        ),
    ]
