# Generated by Django 2.2.1 on 2020-11-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_to_pay', models.FloatField(max_length=15)),
                ('estimated_time', models.FloatField(blank=True, max_length=15, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=15, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=15, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('state', models.CharField(default='en espera', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price_product', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cars.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Product')),
            ],
            options={
                'verbose_name': 'shopping cart',
                'verbose_name_plural': 'shopping carts',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shopping_cars.Order')),
                ('hour_delivery', models.TimeField()),
                ('state', models.CharField(default='no entregado', max_length=255)),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DeliveryMan')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shopping_cars.Order')),
                ('num_bill', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
            },
        ),
    ]
