# Generated by Django 2.2.1 on 2020-11-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_to_pay',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='address_client',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='observation',
        ),
        migrations.AddField(
            model_name='order',
            name='current_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_to_pay',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
